---
title: "Case Study 1"
author: "Nuoya & Meenu"
date: "October 8, 2017"
output: 
  html_document:
      keep_md: true
---

```{r q1, echo = TRUE}

brewery <- read.csv("C:/Users/Dell Eater/Nuoya's/SMU Nuoya/MSDS6306/CaseStudy1/data/raw/Breweries.csv", sep = ',')

numberBrewery <- unique(brewery)
```
```{r q2, echo= TRUE}
beer <- read.csv("C:/Users/Dell Eater/Nuoya's/SMU Nuoya/MSDS6306/CaseStudy1/data/raw/Beers.csv", sep = ',')
colnames(beer) <- c('Name','Beer_ID','ABV','IBU','Brew_ID','Style','Ounces')
brewery$Brew_ID <- rownames(brewery)
mergebeer <- merge(beer,brewery,by = 'Brew_ID',all = FALSE)
mergebeer <- mergebeer[c(3,2,6,4,5,7,1,8,9,10)]
colnames(mergebeer)[2] <- 'Beer Name'
colnames(mergebeer)[8] <- 'Brewery Name'
first6 <- head(mergebeer,6)
last6 <- tail(mergebeer,6)
```

```{r q3, echo= TRUE}
numberNA <- colSums(is.na(mergebeer))
numberNA
```

```{r q4, fig.width=10, fig.height=12, echo= TRUE}
subsetbeer<- data.frame(mergebeer$State,
												mergebeer$ABV,
												mergebeer$IBU)

MedianABV <- tapply(subsetbeer$mergebeer.ABV,subsetbeer$mergebeer.State,median)
MedianIBU <- tapply(subsetbeer$mergebeer.IBU,subsetbeer$mergebeer.State,median)

MedianABV <-data.frame(MedianABV)
MedianIBU <-data.frame(MedianIBU)
finalmedian <- cbind(MedianABV,MedianIBU )

colnames(finalmedian) <- c('Median ABV','Median IBU')
finalmedian$states <- rownames(finalmedian)
finalmedian <- finalmedian[c(3,1,2)]
rownames(finalmedian) <- NULL
finalmedian


par(mar=c(18, 4.1, 4.1, 2.1), mgp=c(3, 1, 0), las=2) #http://rfunction.com/archives/1302

bp <- barplot(finalmedian$`Median ABV`,
      	ylab ='States',
        xlab  ='Median Alcohol Content',
				ylim = c(0,55),
				col = 'blue',
				horiz=T, 
				density = 50,
				las = 1)
```

```{r q5, echo=TRUE}
maxcalculation <- data.frame(mergebeer$ABV,mergebeer$IBU)

colMax <- function(data) {sapply(data, max, na.rm = TRUE)}
colMax(maxcalculation)

maxabv <- mergebeer[which(mergebeer$ABV==0.128),]
maxabv <- maxabv[c(1,2,3,4,5,10)]
maxibu <- mergebeer[which(mergebeer$IBU==138),]
maxibu <- maxibu[c(1,2,3,4,5,10)]
maximum <- rbind(maxabv,maxibu)
maximum
 
```
question 6
```{r q6,echo=TRUE}
summaryABV <- summary(mergebeer$ABV)
summaryABV
```

```{r q7, echo=TRUE}
IBUcontent <- mergebeer$IBU
ABVcontent <- mergebeer$ABV
linearABVIBU <- plot(ABVcontent~IBUcontent)
```

